image: linagora/php-deps-composer:5.6.30

services:
  - mongo:3.2

stages:
  - build
  - build_pkg_deb_jessie
  - build_pkg_deb_stretch
  - build_pkg_rpm
  - deploy_dev

build:
  tags:
    - docker
    - online.net
  stage: build
  script:
    - composer up
    - ./vendor/bin/phpcs -p --standard=vendor/sabre/dav/tests/phpcs/ruleset.xml --report-checkstyle=checkstyle.xml lib/
    - cd tests
    - ../vendor/bin/phpunit --coverage-clover=${CI_PROJECT_DIR}/clover.xml --log-junit=${CI_PROJECT_DIR}/junit.xml .

build_pkg_deb_jessie:
  stage: build_pkg_deb_jessie
  variables:
    GIT_STRATEGY: none
  tags:
    - master
  only:
    - master@linagora/lgs/openpaas/esn-sabre
  script:
    - curl -s -X POST
      -F "token=${BUILD_PACKAGE_CI_TOKEN}"
      -F "ref=master"
      -F "variables[REPO]=https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre.git"
      -F "variables[VERSION_FILE]=composer.json"
      -F "variables[PACKAGE_NAME]=openpaas-davserver"
      -F "variables[DOCKERFILE]=debian/jessie/Dockerfile"
      https://ci.linagora.com/api/v4/projects/338/trigger/pipeline | jq .

build_pkg_deb_stretch:
  stage: build_pkg_deb_stretch
  variables:
    GIT_STRATEGY: none
  tags:
    - master
  only:
    - master@linagora/lgs/openpaas/esn-sabre
  script:
    - curl -s -X POST
      -F "token=${BUILD_PACKAGE_CI_TOKEN}"
      -F "ref=master"
      -F "variables[REPO]=https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre.git"
      -F "variables[VERSION_FILE]=composer.json"
      -F "variables[PACKAGE_NAME]=openpaas-davserver"
      -F "variables[DOCKERFILE]=debian/stretch/Dockerfile"
      https://ci.linagora.com/api/v4/projects/338/trigger/pipeline | jq .

build_pkg_rpm:
  stage: build_pkg_rpm
  variables:
    GIT_STRATEGY: none
  tags:
    - master
  only:
    - master@linagora/lgs/openpaas/esn-sabre
  script:
    - curl -s -X POST
      -F "token=${BUILD_PACKAGE_CI_TOKEN}"
      -F "ref=master"
      -F "variables[REPO]=https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre.git"
      -F "variables[VERSION_FILE]=composer.json"
      -F "variables[PACKAGE_NAME]=openpaas-davserver"
      -F "variables[DOCKERFILE]=redhat/7/Dockerfile"
      https://ci.linagora.com/api/v4/projects/338/trigger/pipeline | jq .

deploy_dev:
  stage: deploy_dev
  tags:
    - dev.open-paas.org
    - deployment
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master@linagora/lgs/openpaas/esn-sabre
  script:
    - cd /srv/sabre.dev
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - composer up
